### ISSUE TITLE
nvda beeps after virtualising in start window

### ISSUE THREAD

**Issue by bdorer** [ruifontes/virtualReview#1]
Using latest NVDA alpha with Windows 10.0.17134
Steps to reproduce
Go into the windows 10 start menu and arrow down
Virtualice window
nvda beeps and produces the following log:
IO - inputCore.InputManager.executeGesture (15:19:09.737):
Input: kb(laptop):control+NVDA+w
IO - tones.beep (15:19:09.753):
Beep at pitch 400, for 300 ms, left volume 50, right volume 50
DEBUGWARNING - scriptHandler.executeScript (15:19:10.061):
error executing script: <bound method GlobalPlugin.script_virtualWindowReview of <globalPlugins.virtualRevision.GlobalPlugin object at 0x05534410>> with gesture u'Strg+NVDA+w'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "addons\virtualRevision\globalPlugins\virtualRevision.py", line 61, in script_virtualWindowReview
  File "\addons\virtualRevision\globalPlugins\virtualRevision.py", line 26, in obtainUWPWindowText
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 713, in _get_simpleFirstChild
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1158, in _get_presentationType
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 642, in _get_presentationType
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1110, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 732, in _getUIACacheablePropertyValue
COMError: (-2147220991, 'Ein Ereignis konnte keinen Abonnenten aufrufen.', (None, None, None, 0, None))

**Comment by josephsl** [comment]
Hi, regarding COM Error, I can’t reproduce this on 1809. Thanks.

**Comment by josephsl** [comment]
Hi, the beep was added to test two things: if it recognizes universal apps, and to give people some kind of progress while trying to load all objects from such windows. I’ll remove this in the next release. Thanks.

**Comment by ruifontes** [comment]
Closed
